
package paquetes;

import java.beans.PropertyVetoException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;


/**
 *
 * @author Usuario
 */
public class ventana extends javax.swing.JFrame {

    /**
     * Creates new form ventana
     */
    public ventana() {
        initComponents();
     id.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jdpescritorio = new javax.swing.JDesktopPane();
        jLabel1 = new javax.swing.JLabel();
        lusuario = new javax.swing.JLabel();
        ltipo = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        id = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem18 = new javax.swing.JMenuItem();
        jMenuItem19 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        itemmatricular = new javax.swing.JMenuItem();
        jMenuItem20 = new javax.swing.JMenuItem();
        itemlistadodocente = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        itemingresarplan = new javax.swing.JMenuItem();
        itemasig = new javax.swing.JMenuItem();
        itemdistricu = new javax.swing.JMenuItem();
        jMenuItem11 = new javax.swing.JMenuItem();
        menuperiodoescolar = new javax.swing.JMenu();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem8 = new javax.swing.JMenuItem();
        menuestructura = new javax.swing.JMenu();
        jMenuItem10 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();
        menuseguridad = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenu7 = new javax.swing.JMenu();
        jMenuItem13 = new javax.swing.JMenuItem();
        itempaseegreso = new javax.swing.JMenuItem();
        itempaseingreso = new javax.swing.JMenuItem();
        menupyc = new javax.swing.JMenu();
        ivercali = new javax.swing.JMenuItem();
        ilibreta = new javax.swing.JMenu();
        jMenuItem23 = new javax.swing.JMenuItem();
        jMenuItem24 = new javax.swing.JMenuItem();
        icalificaciones = new javax.swing.JMenuItem();
        itemregistrarcalificaciones = new javax.swing.JMenuItem();
        itempromocionar = new javax.swing.JMenuItem();
        itemlibrotema = new javax.swing.JMenuItem();
        itemverregistros = new javax.swing.JMenuItem();
        jMenuItem9 = new javax.swing.JMenuItem();
        jMenuItem12 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jdpescritorio.setBackground(new java.awt.Color(0, 204, 204));
        jdpescritorio.setForeground(new java.awt.Color(51, 255, 51));

        jLabel1.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        jLabel1.setText("Bienvenido,");
        jdpescritorio.add(jLabel1);
        jLabel1.setBounds(710, 40, 190, 40);

        lusuario.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        lusuario.setForeground(new java.awt.Color(255, 255, 255));
        lusuario.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lusuario.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jdpescritorio.add(lusuario);
        lusuario.setBounds(900, 40, 440, 40);

        ltipo.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        ltipo.setForeground(new java.awt.Color(255, 255, 255));
        jdpescritorio.add(ltipo);
        ltipo.setBounds(840, 90, 230, 29);

        jLabel4.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel4.setText("Rol de Usuario,");
        jdpescritorio.add(jLabel4);
        jLabel4.setBounds(670, 90, 170, 29);
        jdpescritorio.add(id);
        id.setBounds(800, 130, 90, 20);

        jMenuBar1.setMaximumSize(new java.awt.Dimension(636, 32769));
        jMenuBar1.setPreferredSize(new java.awt.Dimension(636, 40));

        jMenu2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/usuarios.png"))); // NOI18N
        jMenu2.setText("MI PERFIL");
        jMenu2.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N

        jMenuItem2.setText("Cambiar Contraseña");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem2);

        jMenuItem18.setText("Cerrar Sesión");
        jMenuItem18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem18ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem18);

        jMenuItem19.setText("Salir");
        jMenuItem19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem19ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem19);

        jMenuBar1.add(jMenu2);

        jMenu3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/matricular.png"))); // NOI18N
        jMenu3.setText("GESTION MATRICULA");
        jMenu3.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N

        itemmatricular.setText("Matricular Estudiante");
        itemmatricular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemmatricularActionPerformed(evt);
            }
        });
        jMenu3.add(itemmatricular);

        jMenuItem20.setText("Reporte Matriculados");
        jMenuItem20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem20ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem20);

        itemlistadodocente.setText("Listado para Docentes");
        itemlistadodocente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemlistadodocenteActionPerformed(evt);
            }
        });
        jMenu3.add(itemlistadodocente);

        jMenuBar1.add(jMenu3);

        jMenu4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/beca.png"))); // NOI18N
        jMenu4.setText("PLAN DE ESTUDIO");
        jMenu4.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N

        itemingresarplan.setText("Ingresar Plan");
        itemingresarplan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemingresarplanActionPerformed(evt);
            }
        });
        jMenu4.add(itemingresarplan);

        itemasig.setText("Asignaturas");
        itemasig.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemasigActionPerformed(evt);
            }
        });
        jMenu4.add(itemasig);

        itemdistricu.setText("Distribución Curricular");
        itemdistricu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemdistricuActionPerformed(evt);
            }
        });
        jMenu4.add(itemdistricu);

        jMenuItem11.setText("Ver");
        jMenuItem11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem11ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem11);

        jMenuBar1.add(jMenu4);

        menuperiodoescolar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/calendario.png"))); // NOI18N
        menuperiodoescolar.setText("PERIODO ESCOLAR");
        menuperiodoescolar.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        menuperiodoescolar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuperiodoescolarActionPerformed(evt);
            }
        });

        jMenuItem5.setText("Nuevo Ciclo Lectivo");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        menuperiodoescolar.add(jMenuItem5);

        jMenuItem6.setText("Montos de Matriculación");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        menuperiodoescolar.add(jMenuItem6);

        jMenuItem8.setText("Recaudación por Matriculación");
        jMenuItem8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem8ActionPerformed(evt);
            }
        });
        menuperiodoescolar.add(jMenuItem8);

        jMenuBar1.add(menuperiodoescolar);

        menuestructura.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/estructuraescolar.png"))); // NOI18N
        menuestructura.setText("ESTRUCTURA ESCOLAR");
        menuestructura.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N

        jMenuItem10.setText("Niveles");
        jMenuItem10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem10ActionPerformed(evt);
            }
        });
        menuestructura.add(jMenuItem10);

        jMenuItem7.setText("Gestionar Cursos");
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7ActionPerformed(evt);
            }
        });
        menuestructura.add(jMenuItem7);

        jMenuBar1.add(menuestructura);

        menuseguridad.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/seguridad.png"))); // NOI18N
        menuseguridad.setText("SEGURIDAD");
        menuseguridad.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N

        jMenuItem1.setText("Gestionar Personal Autorizado");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        menuseguridad.add(jMenuItem1);

        jMenuItem3.setText("Gestionar Usuario Docente");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        menuseguridad.add(jMenuItem3);

        jMenuItem4.setText("Gestionar Tipo de Usuarios");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        menuseguridad.add(jMenuItem4);

        jMenuBar1.add(menuseguridad);

        jMenu7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/gestion.jpg"))); // NOI18N
        jMenu7.setText("GESTION ESCOLAR");
        jMenu7.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N

        jMenuItem13.setText("Traspaso de División");
        jMenuItem13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem13ActionPerformed(evt);
            }
        });
        jMenu7.add(jMenuItem13);

        itempaseegreso.setText("Gestión de Pases-Egreso-");
        itempaseegreso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itempaseegresoActionPerformed(evt);
            }
        });
        jMenu7.add(itempaseegreso);

        itempaseingreso.setText("Gestión de Pases-Ingreso-");
        itempaseingreso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itempaseingresoActionPerformed(evt);
            }
        });
        jMenu7.add(itempaseingreso);

        jMenuBar1.add(jMenu7);

        menupyc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/prueba.png"))); // NOI18N
        menupyc.setText("PROGRESO Y CALIFICACIONES");
        menupyc.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N

        ivercali.setText("Ver Calificaciones");
        ivercali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ivercaliActionPerformed(evt);
            }
        });
        menupyc.add(ivercali);

        ilibreta.setText("Imprimir Libretas");

        jMenuItem23.setText("L. Parciales");
        jMenuItem23.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem23ActionPerformed(evt);
            }
        });
        ilibreta.add(jMenuItem23);

        jMenuItem24.setText("L. Anuales");
        jMenuItem24.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem24ActionPerformed(evt);
            }
        });
        ilibreta.add(jMenuItem24);

        menupyc.add(ilibreta);

        icalificaciones.setText("Ver Calificaciones ");
        icalificaciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                icalificacionesActionPerformed(evt);
            }
        });
        menupyc.add(icalificaciones);

        itemregistrarcalificaciones.setText("Registrar Calificaciones");
        itemregistrarcalificaciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemregistrarcalificacionesActionPerformed(evt);
            }
        });
        menupyc.add(itemregistrarcalificaciones);

        itempromocionar.setText("Promocionar Alumno");
        itempromocionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itempromocionarActionPerformed(evt);
            }
        });
        menupyc.add(itempromocionar);

        itemlibrotema.setText("Registros de Temas de Clases");
        itemlibrotema.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemlibrotemaActionPerformed(evt);
            }
        });
        menupyc.add(itemlibrotema);

        itemverregistros.setText("Ver Registros de Temas de Clases");
        itemverregistros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemverregistrosActionPerformed(evt);
            }
        });
        menupyc.add(itemverregistros);

        jMenuItem9.setText("Ver Registros de Temas de Clases");
        jMenuItem9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem9ActionPerformed(evt);
            }
        });
        menupyc.add(jMenuItem9);

        jMenuItem12.setText("Imprimir Registros de Temas de Clases");
        jMenuItem12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem12ActionPerformed(evt);
            }
        });
        menupyc.add(jMenuItem12);

        jMenuBar1.add(menupyc);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jdpescritorio, javax.swing.GroupLayout.DEFAULT_SIZE, 1451, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jdpescritorio, javax.swing.GroupLayout.DEFAULT_SIZE, 260, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
       
         nuevacontrasena cl = new nuevacontrasena();
         jdpescritorio.add(cl);
         cl.show();
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem18ActionPerformed
        // TODO add your handling code here:
        this.dispose();
        ingresosistema principal = new ingresosistema();
        principal.setVisible(true);
        principal.pack();
        this.setVisible(false);
    }//GEN-LAST:event_jMenuItem18ActionPerformed

    private void jMenuItem19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem19ActionPerformed
        // TODO add your handling code here:
        System.exit(0);

    }//GEN-LAST:event_jMenuItem19ActionPerformed

    private void itemmatricularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemmatricularActionPerformed
        // TODO add your handling code here:
        // matricularestudiante me=new matricularestudiante();
        // me.setVisible(true);
        //this.dispose();
        gestionmatricula ma = new gestionmatricula();
        this.jdpescritorio.add(ma);
//        try {
//            ma.setMaximum(true);
//        } catch (PropertyVetoException ex) {
//            Logger.getLogger(ventanadirector.class.getName()).log(Level.SEVERE, null, ex);
//        }
        ma.show();

    }//GEN-LAST:event_itemmatricularActionPerformed

    private void jMenuItem20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem20ActionPerformed
        reportmatriculados ud = new reportmatriculados();
        jdpescritorio.add(ud);
        ud.show();
    }//GEN-LAST:event_jMenuItem20ActionPerformed

    private void itemlistadodocenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemlistadodocenteActionPerformed
        // TODO add your handling code here:
        listaparadocente le = new listaparadocente();
        jdpescritorio.add(le);
        le.show();
    }//GEN-LAST:event_itemlistadodocenteActionPerformed

    private void itemingresarplanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemingresarplanActionPerformed
        // Ventana plan curricular
        nplan np = new nplan();
        jdpescritorio.add(np);
        np.show();

    }//GEN-LAST:event_itemingresarplanActionPerformed

    private void itemasigActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemasigActionPerformed
        // ventanaasignaturas
        cargaasignaturas ca = new cargaasignaturas();
        jdpescritorio.add(ca);
        ca.show();
    }//GEN-LAST:event_itemasigActionPerformed

    private void itemdistricuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemdistricuActionPerformed
        // TODO add your handling code here:
        distribucioncurricular dc = new distribucioncurricular();
        jdpescritorio.add(dc);
        dc.show();
    }//GEN-LAST:event_itemdistricuActionPerformed

    private void jMenuItem11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem11ActionPerformed
        // TODO add your handling code here:
        verasignaturas v = new verasignaturas();
        jdpescritorio.add(v);
        v.show();
    }//GEN-LAST:event_jMenuItem11ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        // ventana ciclo lectivo
        ciclolectivo cl = new ciclolectivo();
        jdpescritorio.add(cl);
        cl.show();
        // nuevoclectivo cl =new nuevoclectivo();
        //jdpescritorio.add(cl);
        //cl.show();
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        //ventana  monto de matricula
        costomatricula cm = new costomatricula();
        jdpescritorio.add(cm);
        cm.show();
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void menuperiodoescolarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuperiodoescolarActionPerformed

   }//GEN-LAST:event_menuperiodoescolarActionPerformed

    private void jMenuItem10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem10ActionPerformed
        // TODO add your handling code here:
        niveles n = new niveles();
        jdpescritorio.add(n);
        n.show();
    }//GEN-LAST:event_jMenuItem10ActionPerformed

    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed
        // TODO add your handling code here:
        cursos c = new cursos();
        jdpescritorio.add(c);
        c.show();

    }//GEN-LAST:event_jMenuItem7ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        nusuario1 usu1 = new nusuario1();
        jdpescritorio.add(usu1);
        usu1.show();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
        udocente ud = new udocente();
        jdpescritorio.add(ud);
        ud.show();
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem13ActionPerformed
        // TODO add your handling code here:
        traspasodivision le = new traspasodivision();
        jdpescritorio.add(le);
        le.show();
    }//GEN-LAST:event_jMenuItem13ActionPerformed

    private void ivercaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ivercaliActionPerformed
        // TODO add your handling code here:
       /* JOptionPane.showMessageDialog(null, "¡Usted posee acceso a modificar calificaciones!");
        vercalificaciones vc = new vercalificaciones();
        jdpescritorio.add(vc);
        vc.show();
        vc.trimestre(vercalificaciones.txtidcl.getText());*/
        
        vercalificacionesne cl = new vercalificacionesne();
        jdpescritorio.add(cl);
        cl.show();
    }//GEN-LAST:event_ivercaliActionPerformed

    private void jMenuItem23ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem23ActionPerformed
        // TODO add your handling code here:
        libretasp cm = new libretasp();
        jdpescritorio.add(cm);
        cm.show();
    }//GEN-LAST:event_jMenuItem23ActionPerformed

    private void jMenuItem24ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem24ActionPerformed
        // TODO add your handling code here:
        libretas cm = new libretas();
        jdpescritorio.add(cm);
        cm.show();
    }//GEN-LAST:event_jMenuItem24ActionPerformed

    private void icalificacionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_icalificacionesActionPerformed
        // TODO add your handling code here:
        vercalificacionesne cl = new vercalificacionesne();
        jdpescritorio.add(cl);
        cl.show();
    }//GEN-LAST:event_icalificacionesActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        // TODO add your handling code here:
         tipousuario cl = new tipousuario();
        jdpescritorio.add(cl);
        cl.show();
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void itemregistrarcalificacionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemregistrarcalificacionesActionPerformed
        // TODO add your handling code here:
         registrarcalificacionesok np = new registrarcalificacionesok();
        jdpescritorio.add(np);
        np.show();
        registrarcalificacionesok.iddocente.setText(id.getText());
    }//GEN-LAST:event_itemregistrarcalificacionesActionPerformed

    private void itempaseegresoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itempaseegresoActionPerformed
        // TODO add your handling code here:
        listapaseegreso le = new listapaseegreso();
        jdpescritorio.add(le);
        le.show();
    }//GEN-LAST:event_itempaseegresoActionPerformed

    private void itempaseingresoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itempaseingresoActionPerformed
        // TODO add your handling code here:
         listapaseingreso le = new listapaseingreso();
        jdpescritorio.add(le);
        le.show();
    }//GEN-LAST:event_itempaseingresoActionPerformed

    private void itempromocionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itempromocionarActionPerformed
        // TODO add your handling code here:
         promocionar le = new promocionar();
        jdpescritorio.add(le);
        le.show();
    }//GEN-LAST:event_itempromocionarActionPerformed

    private void itemlibrotemaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemlibrotemaActionPerformed
        // TODO add your handling code here:
        librodetema le = new librodetema();
        jdpescritorio.add(le);
        le.show();
        librodetema.iddocente.setText(id.getText());
    }//GEN-LAST:event_itemlibrotemaActionPerformed

    private void itemverregistrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemverregistrosActionPerformed
        // TODO add your handling code here:
        verlibrodetema le = new verlibrodetema();
        jdpescritorio.add(le);
        le.show();
    }//GEN-LAST:event_itemverregistrosActionPerformed

    private void jMenuItem8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem8ActionPerformed
        // TODO add your handling code here:
         recaudacion le = new recaudacion();
        jdpescritorio.add(le);
        le.show();
    }//GEN-LAST:event_jMenuItem8ActionPerformed

    private void jMenuItem9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem9ActionPerformed
        // TODO add your handling code here:
         verlibrodetema1 le = new verlibrodetema1();
        jdpescritorio.add(le);
        le.show();
    }//GEN-LAST:event_jMenuItem9ActionPerformed

    private void jMenuItem12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem12ActionPerformed
        imprimirlibrodetema le = new imprimirlibrodetema();
        jdpescritorio.add(le);
        le.show();
    }//GEN-LAST:event_jMenuItem12ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
               // new ventana().setVisible(true);
                ventana v = new ventana();
                v.setExtendedState(MAXIMIZED_BOTH);
                v.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JMenuItem icalificaciones;
    public static javax.swing.JLabel id;
    public static javax.swing.JMenu ilibreta;
    public static javax.swing.JMenuItem itemasig;
    public static javax.swing.JMenuItem itemdistricu;
    public static javax.swing.JMenuItem itemingresarplan;
    public static javax.swing.JMenuItem itemlibrotema;
    public static javax.swing.JMenuItem itemlistadodocente;
    public static javax.swing.JMenuItem itemmatricular;
    public static javax.swing.JMenuItem itempaseegreso;
    public static javax.swing.JMenuItem itempaseingreso;
    public static javax.swing.JMenuItem itempromocionar;
    public static javax.swing.JMenuItem itemregistrarcalificaciones;
    public static javax.swing.JMenuItem itemverregistros;
    public static javax.swing.JMenuItem ivercali;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    public static javax.swing.JMenu jMenu4;
    public static javax.swing.JMenu jMenu7;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem11;
    public static javax.swing.JMenuItem jMenuItem12;
    private javax.swing.JMenuItem jMenuItem13;
    private javax.swing.JMenuItem jMenuItem18;
    private javax.swing.JMenuItem jMenuItem19;
    private javax.swing.JMenuItem jMenuItem2;
    public static javax.swing.JMenuItem jMenuItem20;
    private javax.swing.JMenuItem jMenuItem23;
    private javax.swing.JMenuItem jMenuItem24;
    private javax.swing.JMenuItem jMenuItem3;
    public static javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    public static javax.swing.JMenuItem jMenuItem9;
    public static javax.swing.JDesktopPane jdpescritorio;
    public static javax.swing.JLabel ltipo;
    public static javax.swing.JLabel lusuario;
    public static javax.swing.JMenu menuestructura;
    public static javax.swing.JMenu menuperiodoescolar;
    public static javax.swing.JMenu menupyc;
    public static javax.swing.JMenu menuseguridad;
    // End of variables declaration//GEN-END:variables
}
